# theme: minima
remote_theme: jekyll/minima

author:
  name: Pavel Kulmon
  email: "p.kulmon@era.aero"

description: >
  Special repository with support material for our "Accelerating statistical inference and experimental design with machine learning" workshop poster session contribution.

minima:
  skin: dark

header_pages:
  - literature.md
  - people.md
  - era.md

plugins:
  - jekyll-feed
  - jekyll-remote-theme